#!/bin/bash

COMMAND=$1

function usage {
   local exit_code=$1

   echo "Usage: sugar <program>"
   echo "   contains   Prints out files containing expression"
   echo "   uses       Prints out files using file"
   exit $exit_code 
}

if [[ -z "$COMMAND" ]]; then
   usage 1
fi

case $COMMAND in
   "help")
      usage 0
      ;;
   "contains")
      shift 
      sugar-contains "$*"
      ;;
   "uses")
      shift 
      sugar-uses "$*"
      ;;
   *)
      exit "Not supported command: $COMMAND.  See help."
      exit 1
      ;;
esac
